name: proofofdivision
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

dependencies:
  args: ^2.4.2
  crypto: ^3.0.3
  dbcrypt: ^2.0.0
  ecdsa: ^0.0.4
  hex: ^0.2.0
  jaguar_jwt: ^3.0.0
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.5
  shelf_plus: ^1.8.0
  shelf_router: ^1.1.0
  shelf_web_socket: ^1.0.4
  tuple: ^2.0.2

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
